#### This notebook download stock prices from Yahoo Finance

In [5]:
# df_adjOHLCV has data only for NYSE trading days, no weekend data
# df_adjOHLCV includes data for weekends when BTC trades
# read symbols in file to list syms_in_file
# download OHLCV data for symbols in syms_in_file
# drop symbols with all NaN in OHLCV columns from df
# rename column names from ['Open', ..., 'Volume'] to ['open', ..., 'volume']
# drop weekend data by reindex to date index of index_symbol
# pickled df_adjOHLCV
# pickled df_adjOHLCV
# pickled symbols_df_adjOHLCV
# create df_symbols_close, sort df by symbols
# pickled df_symbols_close

In [6]:
# https://stackoverflow.com/questions/67690778/how-to-detect-failed-downloads-using-yfinance
import yfinance as yf
import yfinance.shared as shared
import time
import pandas as pd
# from datetime import date, timedelta, datetime
from myUtils import pickle_dump, pickle_load, read_symbols_file # NOQA
from myUtils import drop_symbols_all_NaN, chunked_list # NOQA
from myUtils import yf_download_AdjOHLCV_noAutoAdj
verbose = False  # True prints more output

# path_dir = "C:/Users/ping/MyDrive/stocks/yfinance/"
path_dir = "G:/My Drive/stocks/yfinance/"
path_data_dump = path_dir + "VSCode_dump/"

# filename_symbols = path_data_dump + 'vg_symbols_4chars_max.csv'  # symbols text file
# filename_symbols = path_data_dump + 'vg_symbols_4chars_max_clean.csv'  # symbols text file
filename_symbols = path_data_dump + 'my_symbols.csv'  # symbols text file

filename_pickled_df_OHLCVA_downloaded = 'df_OHLCVA_downloaded '  # OHLCVA downloaded from Yahoo
filename_pickled_df_adjOHLCV = 'df_adjOHLCV'  # adjusted OHLCV
filename_pickled_df_symbols_close = "df_symbols_close"  # symbols' adjusted close
filename_pickled_symbols_df_adjOHLCV =  'symbols_df_adjOHLCV'  # symbols in df_adjOHLCV

In [7]:
# function to adjust OHLCV
# https://github.com/ranaroussi/yfinance/issues/687
def auto_adjust(data):
    df = data.copy()
    ratio = df["Close"] / df["Adj Close"]
    df["Adj Open"] = df["Open"] / ratio
    df["Adj High"] = df["High"] / ratio
    df["Adj Low"] = df["Low"] / ratio

    df.drop(
        ["Open", "High", "Low", "Close"],
        axis=1, inplace=True)

    df.rename(columns={
        "Adj Open": "Open", "Adj High": "High",
        "Adj Low": "Low", "Adj Close": "Close"
    }, inplace=True)

    # df = df[["Open", "High", "Low", "Close", "Volume"]]
    return df[["Open", "High", "Low", "Close", "Volume"]]

def close_vs_Yahoo (symbols, df):
  for symbol in symbols:
    s = df.iloc[-250]
    
    sDate = s.name.strftime('%Y-%m-%d')
    sClose = s[symbol].Close

    df_sym = yf.Ticker(symbol).history(period='2y')
    # 10:45PM got Adj Close
    yhClose = df_sym.loc[sDate]['Close']

    abs_pct_diff = abs(1 - sClose/yhClose)*100
    print(f'symbol:  {symbol:>4}   Date: {sDate:13}df_Close: {sClose:>10.5f} \
    Yahoo_Close: {yhClose:>10.5f}   %_dif_Close: {abs_pct_diff:>7.5f}')
    if abs_pct_diff > .0001:
      msg_err = f'{symbol}  %_dif_Close > .0001'
      # raise SystemExit(msg_err)
      print(msg_err)  # even if discrepancy, the relative relationship of OHLCV in df_close matches Yahoo_Close
    if symbol == symbols[-1]:
      msg_done = f"No errors found.  Symbols' 'Adjusted Close' matched Yahoo symbols' Close "
      print(msg_done)

In [8]:
# Stop if last date in df_adjOHLCV is the same as Yahoo download
index_symbol = "XOM"  
df_XOM = yf.download(index_symbol)
download_last_date = df_XOM.index[-1].strftime('%Y-%m-%d')
print(f"Full path to pickled df_adjOHLCV:  {path_data_dump}{filename_pickled_df_adjOHLCV}")
print(f'download_last_date: {download_last_date}')
df = pickle_load(path_data_dump, filename_pickled_df_adjOHLCV, verbose=verbose)
df_adjOHLCV_last_date = df.index[-1].strftime('%Y-%m-%d')
print(f'df_adjOHLCV_last_date: {df_adjOHLCV_last_date}')

##########  Allow Repeated Download on the Same Day  ###########################################
# if download_last_date == df_adjOHLCV_last_date:
#   msg_stop = f"df_adjOHLCV is up-to-date,\nlast date from df_adjOHLCV is {df_adjOHLCV_last_date},\nlast date from Yahoo's {index_symbol} download is {download_last_date}"
#   raise SystemExit(msg_stop )
######################################################

[*********************100%***********************]  1 of 1 completed
Full path to pickled df_adjOHLCV:  G:/My Drive/stocks/yfinance/VSCode_dump/df_adjOHLCV
download_last_date: 2024-08-30
df_adjOHLCV_last_date: 2024-06-14

In [9]:
# verify df test_symbols' close against Yahoo
# even if discrepancy, the relative relationship of OHLCV in df_close matches Yahoo_Close
test_symbols = ['A', 'LMT', 'SPY']
_df_list=[]
_df = yf_download_AdjOHLCV_noAutoAdj(test_symbols, verbose=False)
_df_list.append(_df)
_df = pd.concat(_df_list, axis=1)
# get unique symbols from column name
_l_symbols = list(set(_df.columns.get_level_values(0)))
_l_symbols.sort()

_df_adj_list=[]
# adjust OHLC using 'Adj Close'
for symbol in _l_symbols:
  _df1 = auto_adjust(_df[symbol])
  _df_adj_list.append(_df1)

_df_adj = pd.concat(_df_adj_list, axis=1)
_cols = ['Open', 'High', 'Low', 'Close', 'Volume']
# create multilevel column names
_col_names = pd.MultiIndex.from_product([_l_symbols, _cols])
_df_adj.columns = _col_names

close_vs_Yahoo(test_symbols, _df_adj)

[*********************100%***********************]  3 of 3 completed
symbol:     A   Date: 2023-09-05   df_Close:  117.88041     Yahoo_Close:  117.88039   %_dif_Close: 0.00001
symbol:   LMT   Date: 2023-09-05   df_Close:  435.88019     Yahoo_Close:  435.88022   %_dif_Close: 0.00001
symbol:   SPY   Date: 2023-09-05   df_Close:  443.04300     Yahoo_Close:  443.04300   %_dif_Close: 0.00000
No errors found.  Symbols' 'Adjusted Close' matched Yahoo symbols' Close

In [10]:
# read symbols in file to a list and convert to chunks
#  each chunk must have more than 1 symbol, otherwise, symbol won't appear as column name
symbols_in_file = read_symbols_file(filename_symbols)
print(f'symbols in file: {len(symbols_in_file)}')
symbols_add = ['SPY', 'VGT', 'FTEC', 'QQQ', 'VWO', 'VTV', 'BNDX', 'USO', 'JJC', 'BCI', 'NG', 'GBTC', 'BTC-USD', 'ETH-USD', 'SGOV', 'GLD']
print(f'symbols added:   {len(symbols_add)}')
symbols = symbols_in_file + symbols_add
# https://stackoverflow.com/questions/12897374/get-unique-values-from-a-list-in-python
symbols = list(set(symbols))  # keep unique symbols
symbols.sort()  # sort unique symbols in alphabetical order
print(f'unique symbols:  {len(symbols)}')
symbols_chunks = chunked_list(symbols, 400)  # e.g. [['A', 'BB', ...], ['CC', 'DD', ...], ..., ['Z', 'ZWS', ...]]
for chunk in symbols_chunks:
  if len(chunk) == 1:
    raise SystemExit(f'ERROR, Must be more than 1 symbol in each chunk\nsymbols in chunk: {chunk}')

symbols in file: 1578
symbols added:   16
unique symbols:  1587

In [11]:
df_list=[]
symbols_download_err = []
# took 24 minutes to download 1917 symbols without error caused by Yahoo
# for i, symbols in enumerate(symbols_chunks):
for i, symbols in enumerate(symbols_chunks):
  df = yf_download_AdjOHLCV_noAutoAdj(symbols, verbose=False)  
  symbols_download_err.append(list(shared._ERRORS.keys()))
  # print(f'symbols_download_err: {symbols_download_err}')
  print(f'\nsymbols_download_err: {symbols_download_err}')  
  df_list.append(df)
  # pause between download
  if i < len(symbols_chunks) - 1 :  # skip pause after last download
    print(f'downloaded symbols from chuck {i}, sleep start')
    # sleep 78(18m 25s)
    time.sleep(78)
    print(f'downloaded symbols from chuck {i}, sleep ends')
  else:
    print(f'downloaded symbols from all chucks')

print(f'symbols_download_err: {symbols_download_err}')

[*********************100%***********************]  400 of 400 completed

13 Failed downloads:
- AIRC: No data found, symbol may be delisted
- ABC: No data found, symbol may be delisted
- CNHI: No data found, symbol may be delisted
- AAWW: No data found, symbol may be delisted
- ABB: No data found, symbol may be delisted
- ATCO: No data found, symbol may be delisted
- BKI: No data found, symbol may be delisted
- AJRD: No data found, symbol may be delisted
- ATVI: No data found, symbol may be delisted
- CPE: No data found, symbol may be delisted
- DCP: No data found, symbol may be delisted
- BVH: No data found, symbol may be delisted
- CDAY: No data found, symbol may be delisted

symbols_download_err: [['AIRC', 'ABC', 'CNHI', 'AAWW', 'ABB', 'ATCO', 'BKI', 'AJRD', 'ATVI', 'CPE', 'DCP', 'BVH', 'CDAY']]
downloaded symbols from chuck 0, sleep start
downloaded symbols from chuck 0, sleep ends
[*********************100%***********************]  400 of 400 completed

12 Failed downloads:
- DOOR: No data found, symbol may be delisted
- HEP: No data found, symbol may be delisted
- FLT: No data found, symbol may be delisted
- ISEE: No data found, symbol may be delisted
- ICPT: No data found, symbol may be delisted
- DISH: No data found, symbol may be delisted
- FRC: No data found, symbol may be delisted
- ERF: No data found, symbol may be delisted
- IAA: No data found, symbol may be delisted
- HHC: No data found, symbol may be delisted
- HZNP: 1d data not available for startTime=-2208994789 and endTime=1725211030. Only 100 years worth of day granularity data are allowed to be fetched per request.
- KDNY: No data found, symbol may be delisted

symbols_download_err: [['AIRC', 'ABC', 'CNHI', 'AAWW', 'ABB', 'ATCO', 'BKI', 'AJRD', 'ATVI', 'CPE', 'DCP', 'BVH', 'CDAY'], ['DOOR', 'HEP', 'FLT', 'ISEE', 'ICPT', 'DISH', 'FRC', 'ERF', 'IAA', 'HHC', 'HZNP', 'KDNY']]
downloaded symbols from chuck 1, sleep start
downloaded symbols from chuck 1, sleep ends
[*********************100%***********************]  400 of 400 completed

17 Failed downloads:
- MODN: No data found, symbol may be delisted
- NEX: No data found, symbol may be delisted
- OSTK: 1d data not available for startTime=-2208994789 and endTime=1725211138. Only 100 years worth of day granularity data are allowed to be fetched per request.
- MMP: No data found, symbol may be delisted
- MDC: No data found, symbol may be delisted
- NUVA: No data found, symbol may be delisted
- PEAK: No data found, symbol may be delisted
- PACW: No data found, symbol may be delisted
- OFC: No data found, symbol may be delisted
- LSI: No data found, symbol may be delisted
- RE: No data found, symbol may be delisted
- PXD: No data found, symbol may be delisted
- NATI: No data found, symbol may be delisted
- MGI: No data found, symbol may be delisted
- NCR: No data found, symbol may be delisted
- PKI: No data found, symbol may be delisted
- PDCE: 1d data not available for startTime=-2208994789 and endTime=1725211196. Only 100 years worth of day granularity data are allowed to be fetched per request.

symbols_download_err: [['AIRC', 'ABC', 'CNHI', 'AAWW', 'ABB', 'ATCO', 'BKI', 'AJRD', 'ATVI', 'CPE', 'DCP', 'BVH', 'CDAY'], ['DOOR', 'HEP', 'FLT', 'ISEE', 'ICPT', 'DISH', 'FRC', 'ERF', 'IAA', 'HHC', 'HZNP', 'KDNY'], ['MODN', 'NEX', 'OSTK', 'MMP', 'MDC', 'NUVA', 'PEAK', 'PACW', 'OFC', 'LSI', 'RE', 'PXD', 'NATI', 'MGI', 'NCR', 'PKI', 'PDCE']]
downloaded symbols from chuck 2, sleep start
downloaded symbols from chuck 2, sleep ends
[*********************100%***********************]  387 of 387 completed

16 Failed downloads:
- SCHN: No data found, symbol may be delisted
- SGEN: No data found, symbol may be delisted
- TGH: No data found, symbol may be delisted
- TA: No data found, symbol may be delisted
- SJR: No data found, symbol may be delisted
- WWE: No data found, symbol may be delisted
- SYNH: No data found, symbol may be delisted
- TWNK: No data found, symbol may be delisted
- SRC: No data found, symbol may be delisted
- VMW: No data found, symbol may be delisted
- SPLK: No data found, symbol may be delisted
- SEAS: No data found, symbol may be delisted
- SWAV: No data found, symbol may be delisted
- UNVR: No data found, symbol may be delisted
- ROCC: No data found, symbol may be delisted
- TNP: No data found, symbol may be delisted

symbols_download_err: [['AIRC', 'ABC', 'CNHI', 'AAWW', 'ABB', 'ATCO', 'BKI', 'AJRD', 'ATVI', 'CPE', 'DCP', 'BVH', 'CDAY'], ['DOOR', 'HEP', 'FLT', 'ISEE', 'ICPT', 'DISH', 'FRC', 'ERF', 'IAA', 'HHC', 'HZNP', 'KDNY'], ['MODN', 'NEX', 'OSTK', 'MMP', 'MDC', 'NUVA', 'PEAK', 'PACW', 'OFC', 'LSI', 'RE', 'PXD', 'NATI', 'MGI', 'NCR', 'PKI', 'PDCE'], ['SCHN', 'SGEN', 'TGH', 'TA', 'SJR', 'WWE', 'SYNH', 'TWNK', 'SRC', 'VMW', 'SPLK', 'SEAS', 'SWAV', 'UNVR', 'ROCC', 'TNP']]
downloaded symbols from all chucks
symbols_download_err: [['AIRC', 'ABC', 'CNHI', 'AAWW', 'ABB', 'ATCO', 'BKI', 'AJRD', 'ATVI', 'CPE', 'DCP', 'BVH', 'CDAY'], ['DOOR', 'HEP', 'FLT', 'ISEE', 'ICPT', 'DISH', 'FRC', 'ERF', 'IAA', 'HHC', 'HZNP', 'KDNY'], ['MODN', 'NEX', 'OSTK', 'MMP', 'MDC', 'NUVA', 'PEAK', 'PACW', 'OFC', 'LSI', 'RE', 'PXD', 'NATI', 'MGI', 'NCR', 'PKI', 'PDCE'], ['SCHN', 'SGEN', 'TGH', 'TA', 'SJR', 'WWE', 'SYNH', 'TWNK', 'SRC', 'VMW', 'SPLK', 'SEAS', 'SWAV', 'UNVR', 'ROCC', 'TNP']]

In [12]:
# flatten symbols_download_err which is a list-of-lists
l_symbols_err = [val for sublist in symbols_download_err for val in sublist]
pickle_dump(l_symbols_err, path_data_dump, 'l_symbols_err')
l_symbols_err

['AIRC',
 'ABC',
 'CNHI',
 'AAWW',
 'ABB',
 'ATCO',
 'BKI',
 'AJRD',
 'ATVI',
 'CPE',
 'DCP',
 'BVH',
 'CDAY',
 'DOOR',
 'HEP',
 'FLT',
 'ISEE',
 'ICPT',
 'DISH',
 'FRC',
 'ERF',
 'IAA',
 'HHC',
 'HZNP',
 'KDNY',
 'MODN',
 'NEX',
 'OSTK',
 'MMP',
 'MDC',
 'NUVA',
 'PEAK',
 'PACW',
 'OFC',
 'LSI',
 'RE',
 'PXD',
 'NATI',
 'MGI',
 'NCR',
 'PKI',
 'PDCE',
 'SCHN',
 'SGEN',
 'TGH',
 'TA',
 'SJR',
 'WWE',
 'SYNH',
 'TWNK',
 'SRC',
 'VMW',
 'SPLK',
 'SEAS',
 'SWAV',
 'UNVR',
 'ROCC',
 'TNP']

In [13]:
# if l_symbols_err:  # re-download symbols with download error 
#   symbols_download_err = []
#   # took 24 minutes to download 1917 symbols without error caused by Yahoo
#   # for i, symbols in enumerate(symbols_chunks):
#   for i, symbols in enumerate(l_symbols_err):
#     df = yf_download_AdjOHLCV_noAutoAdj(symbols, verbose=False)  
#     symbols_download_err.append(list(shared._ERRORS.keys()))
#     # print(f'symbols_download_err: {symbols_download_err}')
#     print(f'\nsymbols_download_err: {symbols_download_err}')  
#     df_list.append(df)
#     # pause between download
#     if i < len(symbols_chunks) - 1 :  # skip pause after last download
#       print(f'downloaded symbols from chuck {i}, sleep start')
#       # sleep 78(18m 25s)
#       time.sleep(78)
#       print(f'downloaded symbols from chuck {i}, sleep ends')
#     else:
#       print(f'downloaded symbols from all chucks')

#   print(f'symbols_download_err: {symbols_download_err}')

In [14]:
df = pd.concat(df_list, axis=1)
if l_symbols_err:  # if list is not empty, drop symbols with errors
  print(f'l_symbols_err is not empty: {l_symbols_err}')  
  df.drop(l_symbols_err, axis=1, level=0, inplace=True)  # drop symbols with errors

l_symbols = list(set(df.columns.get_level_values(0)))  # get unique symbols
l_symbols.sort()
df = df[l_symbols]  # sort columns by list
print(f"Full path to pickled df_OHLCVA_downloaded:  {path_data_dump}{filename_pickled_df_OHLCVA_downloaded}")
pickle_dump(df, path_data_dump, filename_pickled_df_OHLCVA_downloaded)  # save OHLCA data

l_symbols_err is not empty: ['AIRC', 'ABC', 'CNHI', 'AAWW', 'ABB', 'ATCO', 'BKI', 'AJRD', 'ATVI', 'CPE', 'DCP', 'BVH', 'CDAY', 'DOOR', 'HEP', 'FLT', 'ISEE', 'ICPT', 'DISH', 'FRC', 'ERF', 'IAA', 'HHC', 'HZNP', 'KDNY', 'MODN', 'NEX', 'OSTK', 'MMP', 'MDC', 'NUVA', 'PEAK', 'PACW', 'OFC', 'LSI', 'RE', 'PXD', 'NATI', 'MGI', 'NCR', 'PKI', 'PDCE', 'SCHN', 'SGEN', 'TGH', 'TA', 'SJR', 'WWE', 'SYNH', 'TWNK', 'SRC', 'VMW', 'SPLK', 'SEAS', 'SWAV', 'UNVR', 'ROCC', 'TNP']
Full path to pickled df_OHLCVA_downloaded:  G:/My Drive/stocks/yfinance/VSCode_dump/df_OHLCVA_downloaded

In [15]:
# adjust OHLC
df_adj_list=[]
for symbol in l_symbols:
  _df = auto_adjust(df[symbol])
  df_adj_list.append(_df)

df_adj = pd.concat(df_adj_list, axis=1)
cols = ['Open', 'High', 'Low', 'Close', 'Volume']
col_names = pd.MultiIndex.from_product([l_symbols, cols])  # create multilevel column names
df_adj.columns = col_names  # reindex columns

print(f"Full path to pickled df_adjOHLCV: {path_data_dump}{filename_pickled_df_adjOHLCV}")
pickle_dump(df_adj, path_data_dump, filename_pickled_df_adjOHLCV)  # save adjusted OHLCV data

Full path to pickled df_adjOHLCV: G:/My Drive/stocks/yfinance/VSCode_dump/df_adjOHLCV

In [16]:
df_adjOHLCV = pickle_load(path_data_dump, filename_pickled_df_adjOHLCV)

In [17]:
# drop symbols with all NaN in OHLCV columns from df
df_adjOHLCV, symbols_OHLCV, symbols_dropped = drop_symbols_all_NaN(df_adjOHLCV, verbose)
print(f'symbols with all NaN dropped from df_adjOHLCV: {symbols_dropped}')

Symbol's OHLCV are all NaN: []
symbols with all NaN dropped from df_adjOHLCV: []

In [18]:
# rename columns OHLCV *ONLY AFTER* dropping symbols with all NaN from df,
#   symbols with all NaN has an added AdjClose column and will cause errors  
#  rename column names from ['Open', ..., 'Volume'] to ['open', ..., 'volume']
#  .remove_unused_levels() prevents ValueError
#   e.g ValueError: On level 1, code max (5) >= length of level (5). NOTE: this index is in an inconsistent state
# The error may be caused by removing symbols from the dataframe with all NaN in OHLCV columns
df_adjOHLCV.columns = df_adjOHLCV.columns.remove_unused_levels()
# # set_levels reorders df columns in alphabetical order, so the list of column names also needs to be in alphabetical order
# df_adjOHLCV.columns = df_adjOHLCV.columns.set_levels(['close', 'high', 'low', 'open', 'volume'], level=1)

In [19]:
# drop weekend data by re-indexing to date-index of index_symbol
myNaN = float('nan')
# use Exxon's date as proxy for NYSE trading dates
df_adjOHLCV = df_adjOHLCV.reindex(df_XOM.index, fill_value=myNaN)

In [20]:
# pickle df_adjOHLCV and symbols
# print(f"Full path to pickled df_adjOHLCV_downloaded:  {path_data_dump}{filename_pickled_df_adjOHLCV_downloaded}")
# pickle_dump(df_adjOHLCV_downloaded, path_data_dump, filename_pickled_df_adjOHLCV_downloaded, verbose=verbose)
print(f"Full path to pickled df_adjOHLCV:  {path_data_dump}{filename_pickled_df_adjOHLCV}")
pickle_dump(df_adjOHLCV, path_data_dump, filename_pickled_df_adjOHLCV, verbose=verbose)
print(f"Full path to pickled symbols_df_adjOHLCV:  {path_data_dump}{filename_pickled_symbols_df_adjOHLCV}")
pickle_dump(symbols_OHLCV, path_data_dump, filename_pickled_symbols_df_adjOHLCV, verbose=verbose)

Full path to pickled df_adjOHLCV:  G:/My Drive/stocks/yfinance/VSCode_dump/df_adjOHLCV
Full path to pickled symbols_df_adjOHLCV:  G:/My Drive/stocks/yfinance/VSCode_dump/symbols_df_adjOHLCV

In [21]:
symbols_OHLCV = list(set([i[0] for i in list(df_adjOHLCV)]))
df_symbols_close = df_adjOHLCV.xs('Close', level=1, axis=1)
pickle_dump(df_symbols_close, path_data_dump, filename_pickled_df_symbols_close, verbose=verbose)

In [22]:
# retrieve pickled files

print(f"Full path to pickled df_OHLCVA_downloaded:  {path_data_dump}{filename_pickled_df_OHLCVA_downloaded}")
df_OHLCVA_downloaded = pickle_load(path_data_dump, filename_pickled_df_OHLCVA_downloaded, verbose=verbose)

print(f"Full path to pickled df_adjOHLCV:  {path_data_dump}{filename_pickled_df_adjOHLCV}")
df_adjOHLCV = pickle_load(path_data_dump, filename_pickled_df_adjOHLCV, verbose=verbose)

print(f"Full path to pickled df_symbols_close:  {path_data_dump}{filename_pickled_df_symbols_close}")
df_close = pickle_load(path_data_dump, filename_pickled_df_symbols_close, verbose=verbose)

print(f"Full path to pickled symbols_df_adjOHLCV:  {path_data_dump}{filename_pickled_symbols_df_adjOHLCV}")
symbols_df = pickle_load(path_data_dump, filename_pickled_symbols_df_adjOHLCV, verbose=verbose)

Full path to pickled df_OHLCVA_downloaded:  G:/My Drive/stocks/yfinance/VSCode_dump/df_OHLCVA_downloaded
Full path to pickled df_adjOHLCV:  G:/My Drive/stocks/yfinance/VSCode_dump/df_adjOHLCV
Full path to pickled df_symbols_close:  G:/My Drive/stocks/yfinance/VSCode_dump/df_symbols_close
Full path to pickled symbols_df_adjOHLCV:  G:/My Drive/stocks/yfinance/VSCode_dump/symbols_df_adjOHLCV

In [23]:
print(f'df_OHLCVA_downloaded.info():\n{df_OHLCVA_downloaded.info()}\n')
print(f'df_adjOHLCV.info():\n{df_adjOHLCV.info()}\n')
print(f'df_close.info():\n{df_close.info()}\n')
print(f'len(symbols_df):\n{len(symbols_df)}\n')

<class 'pandas.core.frame.DataFrame'>
Index: 16906 entries, 1962-01-02 00:00:00 to 2024-09-01 00:00:00
Columns: 9174 entries, ('A', 'Open') to ('ZWS', 'Volume')
dtypes: float64(9174)
memory usage: 1.2+ GB
df_OHLCVA_downloaded.info():
None

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 15774 entries, 1962-01-02 to 2024-08-30
Columns: 7645 entries, ('A', 'Open') to ('ZWS', 'Volume')
dtypes: float64(7645)
memory usage: 920.2 MB
df_adjOHLCV.info():
None

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 15774 entries, 1962-01-02 to 2024-08-30
Columns: 1529 entries, A to ZWS
dtypes: float64(1529)
memory usage: 184.1 MB
df_close.info():
None

len(symbols_df):
1529

In [24]:
count_symbols = len(symbols_df)
count_df_close_cols = len(df_close.columns)
count_cols_df_OHLCVA_downloaded = len(df_OHLCVA_downloaded.columns)
count_cols_df_adjOHLCV = len(df_adjOHLCV.columns)
if count_symbols != count_df_close_cols:
  raise SystemExit(f'symbol count: {count_symbols} does not equal df_close column count: {count_df_close_cols}')
if count_symbols * 6 != count_cols_df_OHLCVA_downloaded:
  raise SystemExit(f'6 x symbol count: {6 * count_symbols} does not equal df_OHLCVA_downloaded column count: {count_cols_df_OHLCVA_downloaded}')
if count_symbols * 5 != count_cols_df_adjOHLCV:
  raise SystemExit(f'5 x symbol count: {5 * count_symbols} does not equal df_adjOHLCV column count: {count_cols_df_adjOHLCV}')
print(f'No error found, Column counts in df_close, df_OHLCVA, df_adjOHLCV matched symbol count')

No error found, Column counts in df_close, df_OHLCVA, df_adjOHLCV matched symbol count

In [25]:
print(f'count_symbols: {count_symbols}')
print(f'count_df_close_cols: {count_df_close_cols}')
print(f'count_cols_df_OHLCVA_downloaded: {count_cols_df_OHLCVA_downloaded}')
print(f'count_cols_df_adjOHLCV: {count_cols_df_adjOHLCV}')

count_symbols: 1529
count_df_close_cols: 1529
count_cols_df_OHLCVA_downloaded: 9174
count_cols_df_adjOHLCV: 7645

In [26]:
close_vs_Yahoo(test_symbols, df_adjOHLCV)

symbol:     A   Date: 2023-09-05   df_Close:  117.88040     Yahoo_Close:  117.88041   %_dif_Close: 0.00001
symbol:   LMT   Date: 2023-09-05   df_Close:  435.88022     Yahoo_Close:  435.88019   %_dif_Close: 0.00001
symbol:   SPY   Date: 2023-09-05   df_Close:  443.04297     Yahoo_Close:  443.04300   %_dif_Close: 0.00001
No errors found.  Symbols' 'Adjusted Close' matched Yahoo symbols' Close

In [27]:
_sym = 'NOC'
s_start, s_end = -252, -248
df_adjOHLCV[_sym].iloc[s_start:s_end]
df_OHLCVA_downloaded[_sym].iloc[s_start:s_end]

,Open,High,Low,Close,Adj Close,Volume
Date,,,,,,
2023-12-25 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN
2023-12-26 00:00:00,462.559998,465.760010,462.399994,464.500000,460.559875,420000.0
2023-12-27 00:00:00,462.899994,465.850006,462.600006,464.220001,460.282227,378400.0
2023-12-28 00:00:00,463.399994,467.410004,463.200012,465.679993,461.729828,387700.0

In [28]:
df_adjOHLCV.tail()

                     A                                                 \
                  Open        High         Low       Close     Volume
Date
2024-08-26  141.110001  141.179993  139.960007  140.490005  1013200.0
2024-08-27  140.479996  141.210007  139.710007  141.100006   949700.0
2024-08-28  141.529999  142.309998  140.289993  141.059998  1089900.0
2024-08-29  142.070007  143.440002  141.110001  142.529999  1577400.0
2024-08-30  142.160004  143.270004  141.020004  142.919998  1570700.0

                   AA                                              ...  \
                 Open       High        Low      Close     Volume  ...
Date                                                               ...
2024-08-26  35.000000  35.180000  34.470001  34.560001  5397100.0  ...
2024-08-27  34.349998  35.105000  34.090000  34.299999  3538700.0  ...
2024-08-28  33.189999  33.305000  32.000000  32.090000  7350400.0  ...
2024-08-29  32.209999  32.775002  31.700001  32.470001  4672900.0  ...
2024-08-30  32.500000  32.595001  31.815001  32.099998  3337600.0  ...

                 ZUMZ                                                   ZWS  \
                 Open       High        Low      Close    Volume       Open
Date
2024-08-26  29.100000  29.400000  28.389999  28.490000  304700.0  32.540001
2024-08-27  28.150000  28.520000  27.530001  28.299999  743700.0  32.040001
2024-08-28  28.200001  28.200001  27.580000  28.040001  214700.0  32.029999
2024-08-29  28.080000  28.719999  27.830000  27.879999  227300.0  32.139999
2024-08-30  28.120001  28.120001  27.209999  27.740000  173000.0  32.369999


                 High        Low      Close    Volume
Date
2024-08-26  32.619999  32.060001  32.090000  552500.0
2024-08-27  32.060001  31.719999  32.029999  664100.0
2024-08-28  32.250000  31.860001  31.889999  386400.0
2024-08-29  32.529999  31.850000  32.230000  523500.0
2024-08-30  32.529999  31.940001  32.430000  531400.0

[5 rows x 7645 columns]

In [29]:
syms_def = ['NOC', 'HII', 'AVAV', 'LMT', 'CW', 'HEI']
_df = df_close[syms_def]
_df.tail()

,NOC,HII,AVAV,LMT,CW,HEI
Date,,,,,,
2024-08-26,512.000000,275.567657,177.389999,558.099976,313.899994,245.899994
2024-08-27,512.440002,275.637329,177.759995,560.409973,315.739990,247.389999
2024-08-28,513.559998,278.762909,193.860001,563.979980,312.160004,250.350006
2024-08-29,519.349976,281.559967,203.610001,566.849976,314.399994,255.020004
2024-08-30,523.210022,282.769989,203.759995,568.099976,315.859985,256.559998

In [30]:
syms_LNG = ['LNG', 'CHK', 'GLNG']
_df = df_close[syms_LNG]
_df.tail()

                   LNG        CHK       GLNG
Date
2024-08-26  184.320007  73.889999  32.990002
2024-08-27  184.190002  72.980003  32.869999
2024-08-28  182.520004  71.980003  32.730000
2024-08-29  183.889999  73.989998  33.009998
2024-08-30  185.259995  74.489998  33.290001

In [31]:
_df = df_close[symbols_add]
_df.tail()

,SPY,VGT,FTEC,QQQ,VWO,VTV,BNDX,USO,JJC,BCI,NG,GBTC,BTC-USD,ETH-USD,SGOV,GLD
Date,,,,,,,,,,,,,,,,
2024-08-26,560.789978,574.520020,170.720001,475.339996,44.779999,170.710007,49.880001,77.830002,NaN,19.700001,4.40,50.500000,62880.660156,2681.340576,100.660004,232.759995
2024-08-27,561.559998,577.200012,171.580002,476.760010,44.830002,170.789993,49.849998,76.489998,NaN,19.730000,4.28,49.509998,59504.132812,2458.726562,100.669998,233.389999
2024-08-28,558.299988,569.590027,169.410004,471.350006,44.540001,170.619995,49.830002,75.480003,NaN,19.549999,4.15,46.939999,59027.625000,2528.415527,100.680000,231.750000
2024-08-29,558.349976,568.070007,168.839996,470.660004,44.599998,171.160004,49.799999,76.769997,NaN,19.680000,4.27,47.209999,59388.179688,2528.792725,100.690002,232.949997
2024-08-30,563.679993,573.969971,170.470001,476.269989,44.720001,172.850006,49.759998,74.339996,NaN,19.540001,4.25,46.750000,59119.476562,2525.822021,100.739998,231.289993

In [32]:
# syms_def = ['NOC', 'HII', 'AVAV', 'LMT', 'CW', 'HEI']
s_start, s_end = -252, -247
_df = df_close[test_symbols].iloc[s_start:s_end]
_df

                     A         LMT         SPY
Date
2023-08-31  120.203659  438.974121  444.137665
2023-09-01  121.037651  438.807678  444.966064
2023-09-05  117.880402  435.880219  443.042969
2023-09-06  117.096046  415.074585  440.064636
2023-09-07  115.428070  417.032745  438.713531